version: "3"

services:
  bk-log-folder:
    build: ./log_folder
    volumes:
      - logdata:/usr/app/log_folder

  bk-database:
    build: ./database
    volumes:
      - dbdata:/usr/app/database

  bk-nuxt:
    build:
      context: ./nuxt
      dockerfile: ./Dockerfile
    ports:
      - "${APP_PORT}:3000"
    networks:
      - shared-network
    depends_on:
      - bk-database
    tmpfs:
      - /tmp
    volumes:
      - logdata:/app/log_folder
      - dbdata:/app/database
    environment:
      - NUXT_PORT=3000

volumes:
  logdata:
  dbdata:

networks:
  shared-network:
