version: "3"

services:
  am-log-folder:
    build: ./log_folder
    volumes:
      - logdata:/usr/app/log_folder

  am-database:
    build: ./database
    volumes:
      - dbdata:/usr/app/database

volumes:
  logdata:
  dbdata:

networks:
  shared-network:
