version: "3"

services:
  # bk-log-folder:
  #   build: ./log_folder
  #   volumes:
  #     - logdata:/app/log_folder

  # bk-database:
  #   build: ./database
  #   volumes:
  #     - dbdata:/app/database

  bk-nuxt:
    build:
      context: ./nuxt
      dockerfile: ./Dockerfile
    ports:
      - "${APP_PORT}:3000"
    networks:
      - shared-network
    tmpfs:
      - /tmp
    labels:
      - traefik.enable=true
      - traefik.http.routers.<unique_router_name>.entryPoints=http
      # - "traefik.http.routers.<unique_router_name>.rule=Host(`coolify.io`) && PathPrefix(`/`)"

    # volumes:
    # - logdata:/app/log_folder
    # - dbdata:/app/database
    environment:
      - NUXT_PORT=3000
    # depends_on:
    # - bk-database

volumes:
  logdata:
  dbdata:

networks:
  shared-network:
